# Generated by Django 6.1 on 2026-08-15 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_alter_message_body_alter_message_subject_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="mailing.message",
                verbose_name="Сообщение",
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="recipients",
            field=models.ManyToManyField(
                related_name="campaigns",
                to="mailing.recipient",
                verbose_name="Получатели",
            ),
        ),
    ]
