# Generated by Django 6.1 on 2026-08-16 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_alter_campaign_message_alter_campaign_recipients"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="fail_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Ошибок/не доставлено"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="last_run_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата последней попытки"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaigns",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор рассылки",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="success_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Успешно доставлено"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="total_sent",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Всего отправлено"
            ),
        ),
    ]
