# Generated by Django 6.1 on 2026-08-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0005_alter_campaign_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sendattempt",
            name="error_message",
        ),
        migrations.AddField(
            model_name="sendattempt",
            name="server_response",
            field=models.TextField(blank=True, null=True, verbose_name="Ответ сервера"),
        ),
    ]
