# Generated by Django 6.1 on 2026-08-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0006_remove_sendattempt_error_message_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="fail_count",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="success_count",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="total_sent",
        ),
        migrations.AddField(
            model_name="campaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("Создана", "Создана"),
                    ("Запущена", "Запущена"),
                    ("Завершена", "Завершена"),
                ],
                default="Создана",
                max_length=50,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="end_time",
            field=models.DateTimeField(verbose_name="Дата и время окончания отправки"),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="start_time",
            field=models.DateTimeField(verbose_name="Дата и время начала отправки"),
        ),
    ]
