# Generated by Django 6.1 on 2026-08-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0007_remove_campaign_fail_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sendattempt",
            name="sent_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Время попытки"),
        ),
    ]
